#if !defined(PHYSICS_CONSTANTS)
#define PHYSICS_CONSTANTS

#include <glad/glad.h>
#include <mutex>

const int WINDOW_WIDTH = 800;
const int WINDOW_HEIGHT = 800;
const int PIXEL_COUNT = WINDOW_WIDTH * WINDOW_HEIGHT;
char* PIXEL_BUFFER_A = new char[PIXEL_COUNT];
char* PIXEL_BUFFER_B = new char[PIXEL_COUNT];

const int PHYSICS_SCALE_POWER = 4;
const int PHYSICS_SCALE = 1 << PHYSICS_SCALE_POWER;
const int PHYSICS_WIDTH = WINDOW_WIDTH * PHYSICS_SCALE;
const int PHYSICS_HEIGHT = WINDOW_HEIGHT * PHYSICS_SCALE;

const int REGIONS_ACROSS = 24;
const int REGIONS_DOWN = 24;
const int REGION_WIDTH = PHYSICS_WIDTH / REGIONS_ACROSS;
const int REGION_HEIGHT = PHYSICS_HEIGHT / REGIONS_DOWN;

const GLfloat SIM_SPEED = 2;
const GLfloat ENERGY_LOSS = 0.99;
const GLfloat K_SPRING = 20000 / ENERGY_LOSS;
const GLfloat ENERGY_LOSS_PRIME = 1 - ENERGY_LOSS;
const GLfloat ATTRACTION = 50000;
const GLfloat GRAVITY = 60;

const int PARTICLE_COUNT = 500;
const int PARTICLE_RADIUS = PHYSICS_SCALE * 8;
const int PARTICLE_RADIUS2 = PARTICLE_RADIUS * PARTICLE_RADIUS * 4;
const GLfloat PARTICLE_SPEED = 0;//400;

std::mutex swapMutex;

#endif // PHYSICS_CONSTANTS
